name: Python application

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Conda
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        "${CONDA}/bin/conda" env create -n actiontest
    - name: Lint with flake8
      run: |
        source "${CONDA}/etc/profile.d/conda.sh"
        conda activate actiontest
        flake8 . --show-source --statistics
    - name: Install package
      run: |
        source "${CONDA}/etc/profile.d/conda.sh"
        conda activate actiontest
        python3 setup.py install
    - name: Test with pytest
      run: |
        source "${CONDA}/etc/profile.d/conda.sh"
        conda activate actiontest
        pytest --cov hello
        coverage run -a --source=hello "$(command -v hello)"
        coverage run -a --source=hello "$(command -v hello)" Earth
        coverage report --fail-under=90
    - name: Test import Iris
      run: |
        source "${CONDA}/etc/profile.d/conda.sh"
        conda activate actiontest
        python3 -m irisversion
