name: Python application

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Conda
    - run: conda env create -n actiontest
    - name: Lint with flake8
    - run: |
        conda activate actiontest
        flake8 . --show-source --statistics
    - name: Install package
      run: |
        conda actiontest actiontest
        python3 setup.py install
    - name: Test with pytest
      run: |
        conda actiontest actiontest
        pytest --cov hello
        coverage run -a $(command -v hello)
        coverage run -a $(command -v hello) Earth
        coverage report --fail-under=90
    - name: Test import Iris
      run: |
        conda actiontest actiontest
        python3 -m irisversion
